### ISSUE TITLE
mesh subdir of BrickModels does not exist in unpacked client

### ISSUE THREAD

**Issue by HailStorm32** [DarkflameUniverse/NexusDashboard#27]
`properties.py` looks for models in the `mesh` subdir of `BrickModels`. However the `BrickModels` dir from the unpacked client does not contain these sub directories. Instead all model files are in the root dir of `BrickModels`

```[2022-03-31 04:31:53 +0000] [11012] [INFO] admin Logged in
[2022-03-31 04:32:11 +0000] [11009] [ERROR] ERROR on app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_screen.lod1.mtl:
 [Errno 2] No such file or directory: 'app/luclient/res/BrickModels/mesh/reward/rew_ninjagomonastery_screen.lxfml'
[2022-03-31 04:32:11 +0000] [11011] [ERROR] ERROR on app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_walloutsidecorner1.lod1.mtl:
 [Errno 2] No such file or directory: 'app/luclient/res/BrickModels/mesh/reward/rew_ninjagomonastery_walloutsidecorner1.lxfml'
[2022-03-31 04:32:12 +0000] [11011] [ERROR] Exception on /properties/get_model/70368744182634/mtl/1 [GET]
Traceback (most recent call last):
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask_user/decorators.py", line 58, in decorator
    return view_function(*args, **kwargs)
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 315, in get_model
    response = prebuilt(content, file_format, lod)[0]
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 381, in prebuilt
    with open(str(cache.as_posix()), 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_walloutsidecorner1.lod1.mtl'
[2022-03-31 04:32:12 +0000] [11009] [ERROR] Exception on /properties/get_model/70368744182661/mtl/1 [GET]
Traceback (most recent call last):
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask_user/decorators.py", line 58, in decorator
    return view_function(*args, **kwargs)
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 315, in get_model
    response = prebuilt(content, file_format, lod)[0]
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 381, in prebuilt
    with open(str(cache.as_posix()), 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_screen.lod1.mtl'
[2022-03-31 04:32:12 +0000] [11012] [ERROR] ERROR on app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_wall4.lod1.mtl:
 [Errno 2] No such file or directory: 'app/luclient/res/BrickModels/mesh/reward/rew_ninjagomonastery_wall4.lxfml'
[2022-03-31 04:32:12 +0000] [11012] [ERROR] Exception on /properties/get_model/70368744182652/mtl/1 [GET]
Traceback (most recent call last):
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask_user/decorators.py", line 58, in decorator
    return view_function(*args, **kwargs)
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 315, in get_model
    response = prebuilt(content, file_format, lod)[0]
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 381, in prebuilt
    with open(str(cache.as_posix()), 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_wall4.lod1.mtl'
[2022-03-31 04:32:12 +0000] [11010] [ERROR] ERROR on app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_wallinsidecorner1.lod1.mtl:
 [Errno 2] No such file or directory: 'app/luclient/res/BrickModels/mesh/reward/rew_ninjagomonastery_wallinsidecorner1.lxfml'
[2022-03-31 04:32:12 +0000] [11010] [ERROR] Exception on /properties/get_model/70368744182640/mtl/1 [GET]
Traceback (most recent call last):
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/[redacted]/.local/lib/python3.9/site-packages/flask_user/decorators.py", line 58, in decorator
    return view_function(*args, **kwargs)
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 315, in get_model
    response = prebuilt(content, file_format, lod)[0]
  File "/home/[redacted]/NexusDashboard/app/properties.py", line 381, in prebuilt
    with open(str(cache.as_posix()), 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'app/cache/BrickModels/mesh/reward/rew_ninjagomonastery_wallinsidecorner1.lod1.mtl' 
```

![image](https://user-images.githubusercontent.com/5051025/160978459-4bd990c1-d6dc-4d46-b7c5-a1dd6388f178.png)

**Comment by aronwk-aaron** [comment]
ah ha, I was seeing this issue, but didn't have time to track it down yet.
I think I know what the problem is
