### ISSUE TITLE
Error when opening properties tab

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/NexusDashboard#48]
A popup appears whenever I open the properties tab or any page involving properties. A restart will return things to normal, but only temporarily as it just comes back up again not much later.

![image](https://user-images.githubusercontent.com/48499798/182705929-be51c9f7-cac5-4a1d-a6ba-252716308c50.png)

**Comment by aronwk-aaron** [comment]
make sure you run migrations

**Comment by MustacheMan2** [comment]
I haven't seen any migrations come up recently, what could I be missing?

**Comment by aronwk-aaron** [comment]
please refer to the system log page for more detailed errors, if you post that I will look into  the issue, but there are no issues here, so could just be your server stalling  after awhile or some environmental issue

**Comment by MustacheMan2** [comment]
2022-08-04 18:27:22,232 - app - ERROR - Exception on /properties/get/all [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_user/decorators.py", line 58, in decorator
return view_function(*args, **kwargs)
File "/root/NexusDashboard/app/__init__.py", line 280, in wrapper
return func(*args, **kwargs)
File "/root/NexusDashboard/app/properties.py", line 213, in get
print(data)
OSError: [Errno 5] Input/output error

**Comment by aronwk-aaron** [comment]
update your dashboard

**Comment by MustacheMan2** [comment]
this is the latest commit though

**Comment by aronwk-aaron** [comment]
restart then
that code doesn't exist in the current app

**Comment by MustacheMan2** [comment]
I don't want to be a bother about this, but this issue continues to happen. Redid everything twice and it just starts happening again shortly after. It's gotten to the point where I have to go through multiple popups for the other unmoderated things to show up when pressing that tab, and viewing the properties tab simply does not work anymore. Beginning to think it might be some error with the db, as it's been around since DLU's launch, but not sure how to go on from there.
